Repository conjurdemos/conjur-intro, pull requests merged in 2018-11, with the labels that each got.

#14 Add auto-failover to demo
  demos/auto-failover/cli
  demos/aws-authentication/jason-conjur-test.pem
  demos/simple-cluster/README.md
  demos/simple-cluster/cli
  demos/simple-cluster/docker-compose.yml
  demos/simple-cluster/files/certs/conjur-master-1.mycompany.local.cert.pem
  demos/simple-cluster/files/certs/conjur-master-1.mycompany.local.key.pem
  demos/simple-cluster/files/certs/conjur-master-2.mycompany.local.cert.pem
  demos/simple-cluster/files/certs/conjur-master-2.mycompany.local.key.pem
  demos/simple-cluster/files/certs/conjur-master-3.mycompany.local.cert.pem
  demos/simple-cluster/files/certs/conjur-master-3.mycompany.local.key.pem
  demos/simple-cluster/files/certs/conjur-master-4.mycompany.local.cert.pem
  demos/simple-cluster/files/certs/conjur-master-4.mycompany.local.key.pem
  demos/simple-cluster/files/haproxy/haproxy-bu.cfg
  demos/simple-cluster/policy/cluster.yml
  demos/simple-cluster/policy/root.yml
  demos/simple-cluster/start
  load-modular
  tools/simple-certificates/generate_certificates
Labels: in progress

#15 Adds Load balancer in front of cluster
  demos/simple-cluster/cli
  demos/simple-cluster/docker-compose.yml
  demos/simple-cluster/files/certs/ca-chain.cert.pem
  demos/simple-cluster/files/certs/conjur-follower-1.mycompany.local.cert.pem
  demos/simple-cluster/files/certs/conjur-follower-1.mycompany.local.key.pem
  demos/simple-cluster/files/certs/conjur-follower.mycompany.local.cert.pem
  demos/simple-cluster/files/certs/conjur-follower.mycompany.local.key.pem
  demos/simple-cluster/files/certs/conjur-master-1.mycompany.local.cert.pem
  demos/simple-cluster/files/certs/conjur-master-1.mycompany.local.key.pem
  demos/simple-cluster/files/certs/conjur-master-2.mycompany.local.cert.pem
  demos/simple-cluster/files/certs/conjur-master-2.mycompany.local.key.pem
  demos/simple-cluster/files/certs/conjur-master-3.mycompany.local.cert.pem
  demos/simple-cluster/files/certs/conjur-master-3.mycompany.local.key.pem
  demos/simple-cluster/files/certs/conjur-master-4.mycompany.local.cert.pem
  demos/simple-cluster/files/certs/conjur-master-4.mycompany.local.key.pem
  demos/simple-cluster/files/certs/conjur-master.mycompany.local.cert.pem
  demos/simple-cluster/files/certs/conjur-master.mycompany.local.key.pem
  demos/simple-cluster/files/haproxy/haproxy-bu.cfg
  demos/simple-cluster/files/haproxy/haproxy.cfg
  demos/simple-cluster/start
  tools/simple-certificates/README.md
  tools/simple-certificates/generate_certificates
Labels: in progress

#16 Revert "Adds Load balancer in front of cluster"
  demos/simple-cluster/cli
  demos/simple-cluster/docker-compose.yml
  demos/simple-cluster/files/certs/ca-chain.cert.pem
  demos/simple-cluster/files/certs/conjur-follower-1.mycompany.local.cert.pem
  demos/simple-cluster/files/certs/conjur-follower-1.mycompany.local.key.pem
  demos/simple-cluster/files/certs/conjur-follower.mycompany.local.cert.pem
  demos/simple-cluster/files/certs/conjur-follower.mycompany.local.key.pem
  demos/simple-cluster/files/certs/conjur-master-1.mycompany.local.cert.pem
  demos/simple-cluster/files/certs/conjur-master-1.mycompany.local.key.pem
  demos/simple-cluster/files/certs/conjur-master-2.mycompany.local.cert.pem
  demos/simple-cluster/files/certs/conjur-master-2.mycompany.local.key.pem
  demos/simple-cluster/files/certs/conjur-master-3.mycompany.local.cert.pem
  demos/simple-cluster/files/certs/conjur-master-3.mycompany.local.key.pem
  demos/simple-cluster/files/certs/conjur-master-4.mycompany.local.cert.pem
  demos/simple-cluster/files/certs/conjur-master-4.mycompany.local.key.pem
  demos/simple-cluster/files/certs/conjur-master.mycompany.local.cert.pem
  demos/simple-cluster/files/certs/conjur-master.mycompany.local.key.pem
  demos/simple-cluster/files/haproxy/haproxy-bu.cfg
  demos/simple-cluster/files/haproxy/haproxy.cfg
  demos/simple-cluster/start
  tools/simple-certificates/README.md
  tools/simple-certificates/generate_certificates
Labels: in progress

#18 Secure LDAP Sync Demo
  .gitignore
  demos/ldap-integration/.gitignore
  demos/ldap-integration/README.md
  demos/ldap-integration/certs/.gitkeep
  demos/ldap-integration/cli
  demos/ldap-integration/docker-compose.yml
  demos/ldap-integration/files/ldap/disable_anon_backend.ldif
  demos/ldap-integration/files/ldap/disable_anon_frontend.ldif
  demos/ldap-integration/files/ldap/test-ldap_groups.ldif
  demos/ldap-integration/files/ldap/test-ldap_users.ldif
  demos/ldap-integration/files/ldap/test-perf_1000u_100g.ldif
  demos/ldap-integration/policy/01_root.yml
  demos/ldap-integration/policy/02_ldap_sync.yml
  demos/ldap-integration/policy/03_authn_ldap.yml
  demos/ldap-integration/start
  demos/ldap-integration/stop
Labels: review

#20 Add ability to generate long cert chains
  .gitignore
  tools/simple-certificates/Dockerfile
  tools/simple-certificates/README.md
  tools/simple-certificates/configs/openssl.cnf
  tools/simple-certificates/configs/root-openssl.cnf
  tools/simple-certificates/generate_certificates
Labels: implementing

#21 Update LDAP demo to use secure LDAP authentication
  demos/ldap-integration/.gitignore
  demos/ldap-integration/README.md
  demos/ldap-integration/certs/ca-chain.crt
  demos/ldap-integration/certs/ca.crt
  demos/ldap-integration/certs/ldap.crt
  demos/ldap-integration/certs/ldap.key
  demos/ldap-integration/docker-compose.yml
  demos/ldap-integration/files/ldap/test-ldap_groups.ldif
  demos/ldap-integration/files/ldap/test-ldap_users.ldif
  demos/ldap-integration/policy/02_ldap_sync.yml
  demos/ldap-integration/policy/03_authn_ldap.yml
  demos/ldap-integration/policy/04_authn_ldap_entitlements.yml
  demos/ldap-integration/start
  demos/ldap-integration/stop
Labels: implemented

#26 Update ldap integration image
  demos/ldap-integration/docker-compose.yml
  demos/ldap-integration/start
Labels: implementing

#27 Include LDAP Integration demo in root README
  README.md
Labels: implementing
